import fs from "node:fs";
import path from "node:path";

import {
  buildByenAliasMap,
  buildByenRows,
  buildRegionMaps,
  type ByenAliasRecord,
  type ByenLedgerRecord,
  type RegionenLedgerRecord,
} from "./visitationLedgerModel";

const ROOT = path.resolve(__dirname, "..");
const BYEN_LEDGER = path.join(ROOT, "docs", "visitation-review", "byen-ledger.json");
const BYEN_ALIASES = path.join(ROOT, "docs", "visitation-review", "byen-aliases.json");
const REGION_LEDGER = path.join(ROOT, "docs", "visitation-review", "regionen-ledger.json");
const GENERATED = path.join(
  ROOT,
  "src",
  "features",
  "destination",
  "data",
  "generated",
  "visitationData.ts",
);

function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(file, "utf8")) as T;
}

function render(value: unknown): string {
  return JSON.stringify(value, null, 2)
    .replace(/"([^"\\]+)":/g, (_, key: string) =>
      /^[A-Za-z_$][\w$]*$/.test(key) ? `${key}:` : `${JSON.stringify(key)}:`,
    )
    .replace(/"([^"\\]*)"/g, (_, value: string) => JSON.stringify(value));
}

export function generateVisitationData(): string {
  const byenLedger = readJson<ByenLedgerRecord[]>(BYEN_LEDGER);
  const byen = buildByenRows(byenLedger);
  const aliases = buildByenAliasMap(
    byenLedger,
    readJson<ByenAliasRecord[]>(BYEN_ALIASES),
  );
  const region = buildRegionMaps(readJson<RegionenLedgerRecord[]>(REGION_LEDGER));

  return [
    "// Generated by scripts/generateVisitationData.ts.",
    "// Do not edit: update the reviewed ledgers and regenerate.",
    'import type { HospitalCode, RawStreetRow, RegionCategory } from "../../types";',
    "",
    `export const GENERATED_BYEN_STREET_ROWS: readonly RawStreetRow[] = ${render(byen)};`,
    "",
    `export const GENERATED_BYEN_STREET_ALIASES: Readonly<Record<string, string>> = ${render(aliases)};`,
    "",
    `export const GENERATED_REGION_MAPS = ${render(region)} as Record<`,
    '  "nord" | "midt" | "byen" | "syd",',
    "  Record<string, Record<RegionCategory, HospitalCode>>",
    ">;",
    "",
  ].join("\n");
}

if (require.main === module) {
  const output = generateVisitationData();
  fs.mkdirSync(path.dirname(GENERATED), { recursive: true });
  fs.writeFileSync(GENERATED, output, "utf8");
  process.stdout.write(`Generated ${path.relative(ROOT, GENERATED)}\n`);
}
